# This sets the folder where Netlify will find your functions
[build]
  functions = "netlify/functions"

# This specifically targets our "proxy" function and sets its timeout
[functions.proxy]
  timeout = 26
